#spring.application.name=ecommerce-multyvendor
#server.port=5000
#spring.jpa.hibernate.ddl-auto=update
##spring.datasource.url=jdbc:mysql://localhost:3306/hs_ecommerce
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/hs_ecommerce
#spring.datasource.username=root
#spring.datasource.password=hatrik
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#razorpay.api.key=rzp_test_RlCbSMM7Y05xi7
#razorpay.api.secret=WVJHlE0zKdJOH5NVQ9r1Bz61
#stripe.api.key=dummy_value
#stripe.webhook.secret=dummy_value

spring.application.name=ecommerce-multyvendor
server.port=5000

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

razorpay.api.key=rzp_test_RlCbSMM7Y05xi7
razorpay.api.secret=WVJHlE0zKdJOH5NVQ9r1Bz61

stripe.api.key=dummy_value
stripe.webhook.secret=dummy_value

#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=587
#
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.enable=false
#spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
#
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#
#spring.mail.properties.mail.debug=true

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

# SSL ON (IMPORTANT)
spring.mail.properties.mail.smtp.ssl.enable=true

# STARTTLS OFF
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.debug=true
